name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Setup Go environment
      uses: actions/setup-go@v6.0.0
      with:
        go-version: 1.24

    - name: Get dependencies
      run: go mod vendor

    - name: Build
      run: make

    - name: Run tests
      run: make test